### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by winixt** [ssddanbrown/codemirror-lang-twig#1]
@digit and @eof is not defined?

 Unexpected token '@digit'

**Comment by ssddanbrown** [comment]
Hi, There's not a lot of information here.
To be able to help further, I'd need to understand exactly what you're trying to do, so exact steps taken or command ran to get to the error.

**Comment by ssddanbrown** [comment]
I'm gonna close this off but feel free to still respond to the above if needed.
